title: Douglas Day's Blog
author: DDay
email: douglasday@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Seeker of Truth. Forever a student. Truth is at the intersection of Athens & Jerusalem.
  
# social links
twitter_username: archangeldday # DO NOT include the @ character, or else the build will fail!
github_username:  douglasday # DO NOT include the @ character, or else the build will fail!


plugins:
  - jekyll-include-cache

show_excerpts: true # set to false to remove excerpts on the homepage

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

#theme: jekyll-theme-midnight
#minima:
#  skin: dark
