title: Douglas Day Blog
author: DDay
email: douglasday@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thanks for viewing my blog! In an attempt to #learnInPublic, I'll start documenting my thoughts and learning processes here on this blog. Hope you enjoy!
  
# social links
twitter_username: archangeldday # DO NOT include the @ character, or else the build will fail!
github_username:  douglasday # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-slate
